name: pspdecrypt for ARK 5 ( DAM )
on:
  push:
    branches:
      - master
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang automake autoconf p7zip-full automake -y

      - name: Build
        run: make clean && make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: linux-binaries
          path: pspdecrypt
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
             install: >-
                base-devel
                git
                mingw-w64-x86_64-clang
                mingw-w64-x86_64-openssl
      - uses: actions/checkout@v7
      - name: Makes Binaries
        run: make EXTRA_FLAG=-static
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: windows-binaries
          path: pspdecrypt
        
  build-macos-x86:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v7
    - name: Make binaries
      run: |
        export LIBRARY_PATH=$LIBRARY_PATH:$(brew --prefix openssl)/lib
        export CPLUS_INCLUDE_PATH=$INCLUDE_PATH:$(brew --prefix openssl)/include
        make CXX='clang++ -std=c++11 -target x86_64-apple-darwin-macho'
    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: macos-intel-binaries
        path: pspdecrypt

  build-macos-universal:
    needs: build-macos-x86
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v7
    - name: Make binaries
      run: |
        export LIBRARY_PATH=$LIBRARY_PATH:$(brew --prefix openssl)/lib
        export CPLUS_INCLUDE_PATH=$INCLUDE_PATH:$(brew --prefix openssl)/include
        make CXX='clang++ -std=c++11 -target arm64-apple-darwin20.1.0'
    - name: Download Artifact
      uses: actions/download-artifact@v8
      with:
        name: macos-intel-binaries
        path: artifact
    - name: Make Universal Binary
      run: |
        lipo pspdecrypt ~/work/pspdecrypt/pspdecrypt/artifact/pspdecrypt -create -output pspdecrypt
        rm -rf ~/work/pspdecrypt/pspdecrypt/artifact/
