name: pspdecrypt for ARK 5 ( DAM )
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang automake autoconf p7zip-full automake -y

      - name: Build
        run: make clean && make
      - name: Compress
        run: |
          zip -r pspdecrypt.zip pspdecrypt
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: pspdecrypt-release
          path: pspdecrypt.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: pspdecrypt-release
          path: .
      - name:
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          files: pspdecrypt.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


